### ISSUE TITLE
low accuracy

### ISSUE THREAD

**Issue by Munduruca** [TsMedia/sentiment-analysis--w-tflearn#1]
Thank you for sharing your work!

![2017-07-04_17-41-13](https://user-images.githubusercontent.com/7276970/27820014-105168b6-60e0-11e7-803c-d44db865f6a2.png)

![2017-07-04_17-46-51](https://user-images.githubusercontent.com/7276970/27820184-e4e6e07e-60e0-11e7-9e90-3a1115244bfa.png)

when I run the notebook the training accuracy never goes beyond 52%.
Naturally, the test accuracy is around 50% and the predictions are not so good...
would you know what can cause it?

**Comment by yaak-tg** [comment]
Hi Ricardo, If there is no problem in your model, the accuracy around 50% can be caused by keeping words with high frequency in both comments. Try to drop less frequent words in another point to see if it changes the accuracy.
